
version: 2

models:
  - name: delayed_deliveries
    description: "A starter dbt model"
    columns:
      - name: country
        description: "The name of country"
        tests:
          - not_null
      - name: postal_code
        description: "the name of postal code"
        tests:
          - unique
      - name: date_valid_std
        description: "The date when we deliver the package"
      - name: tot_snowfall_in
        description: "The total snowfall"
